# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

# build version format
version: "{build}"

# fix lineendings in Windows
init:
  - git config --global core.autocrlf input

# what combinations to test
environment:
  matrix:
  - nodejs_version: 0.10
  - nodejs_version: 0.12

# combinations having this can fail
# matrix:
#   allow_failures:
#   - nodejs_version: 0.11

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - npm install -g gulp
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - npm test --no-color
